server:
    port: 8080

db:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    username: 'postgres'
    password: 'postgres'
    database: 'test_live_db'
    logging: false
    synchronize: false
    migration: true

tables:
    table1: 'users'
    table2: 'admins'

graphql:
    playground: true

jwt:
    secret: 'Secret666'